"""init

Revision ID: f84ef78986e0
Revises: 
Create Date: 2024-04-23 21:57:05.337702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f84ef78986e0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_members',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('chat_id', sa.BIGINT(), nullable=False),
    sa.Column('warns', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chats',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('is_group', sa.Boolean(), nullable=False),
    sa.Column('language', sa.String(length=3), nullable=False),
    sa.Column('warns_limit', sa.Integer(), nullable=False),
    sa.Column('warns_action', sa.String(), nullable=False),
    sa.Column('warns_action_time', sa.BIGINT(), nullable=False),
    sa.Column('default_mute_time', sa.BIGINT(), nullable=False),
    sa.Column('default_ban_time', sa.BIGINT(), nullable=False),
    sa.Column('new_participant_greeting', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chats')
    op.drop_table('chat_members')
    # ### end Alembic commands ###
